# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/hdmi_out_PmodENC_0_0.xci
# IP: The module: 'hdmi_out_PmodENC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodENC_pmod_bridge_0_0}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlslice_0_0/PmodENC_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_0 || ORIG_REF_NAME==PmodENC_xlslice_0_0}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlslice_0_1/PmodENC_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_1 || ORIG_REF_NAME==PmodENC_xlslice_0_1}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlslice_0_2/PmodENC_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_2 || ORIG_REF_NAME==PmodENC_xlslice_0_2}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlslice_t_0_0/PmodENC_xlslice_t_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_t_0_0 || ORIG_REF_NAME==PmodENC_xlslice_t_0_0}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlconcat_0_0/PmodENC_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlconcat_0_0 || ORIG_REF_NAME==PmodENC_xlconcat_0_0}]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodENC_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/hdmi_out_PmodENC_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_PmodENC_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_PmodENC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0}] {/U0 }]/U0 ]]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/hdmi_out_PmodENC_0_0.xci
# IP: The module: 'hdmi_out_PmodENC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodENC_pmod_bridge_0_0}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlslice_0_0/PmodENC_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_0 || ORIG_REF_NAME==PmodENC_xlslice_0_0}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlslice_0_1/PmodENC_xlslice_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_1 || ORIG_REF_NAME==PmodENC_xlslice_0_1}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlslice_0_2/PmodENC_xlslice_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_2 || ORIG_REF_NAME==PmodENC_xlslice_0_2}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlslice_t_0_0/PmodENC_xlslice_t_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_t_0_0 || ORIG_REF_NAME==PmodENC_xlslice_t_0_0}]

# IP: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_xlconcat_0_0/PmodENC_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlconcat_0_0 || ORIG_REF_NAME==PmodENC_xlconcat_0_0}]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodENC_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/hdmi_out_PmodENC_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_PmodENC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_PmodENC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/Ilde/Desktop/Zybo-hdmi-out/src/bd/hdmi_out/ip/hdmi_out_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0}] {/U0 }]/U0 ]]
